### ISSUE TITLE
I wonder which is your julia verision

### ISSUE THREAD

**Issue by zhang-shubai** [JuliaComputing/ToyFHE.jl#10]
I'm using julia 1.0.0 to run your code in Ubuntu18.04
however, when i input "include("train.jl")"
I encounter some problems:
![2020-01-14 21-35-21 的屏幕截图](https://user-images.githubusercontent.com/30946222/72348661-d7a55900-3715-11ea-974a-0c099bf369d1.png)
I guess that I use diferent version, so i wonder which version is your julia.'
Thank you!

**Comment by Keno** [comment]
Should work fine on 1.3.

**Comment by StefanKarpinski** [comment]
Maybe worth putting `[compat]` in your project file to indicate this?

**Comment by Keno** [comment]
Looks like the problem is in CuArrays though

**Comment by MingqinHan** [comment]
> Looks like the problem is in CuArrays though

Have you solved this problem?

**Comment by zhang-shubai** [comment]
Hello, I fix it!
I thought that I have installed CUDA & cuDNN, however, I was wrong.
After the install CUDA 10.1 & cuDNN 7.6.4.38, some tiny probelms arise, but you can refer to FluxML/Flux.jl#918.
Now I close it.
